batch: possibly use a web browser to convert ABC to PDF

diff --git a/abctopdf b/abctopdf
--- a/abctopdf
+++ b/abctopdf
@@ -18,12 +18,6 @@ EOF
 	exit 1
 fi
 
-# check the required programs
-if ! command -v rsvg-convert >/dev/null 2>&1; then
-	echo "$0: program 'rsvg-convert' not found - abort"
-	exit 1
-fi
-
 # choose a abc2svg batch script with an available JS interpreter
 if [ ${0#./} != $0 ]; then
 	bdir="./"
@@ -68,17 +62,36 @@ echo "Using $abcscr"
 # default name
 out='abc.pdf'
 n=0
-	for a do
-		if [ "$a" = "-o" ]; then
-			n=1
-		elif [ $n -eq 1 ]; then
-			out=$a
-			n=0
-		else
-			set -- "$@" "$a"
-		fi
-		shift
-	done
+for a do
+	if [ "$a" = "-o" ]; then
+		n=1
+	elif [ $n -eq 1 ]; then
+		out=$a
+		n=0
+	else
+		set -- "$@" "$a"
+	fi
+	shift
+done
+
+# check if some chromium-based browser is available
+for c in chromium vivaldi opera brave epic chrome end; do
+	if command -v $c >/dev/null 2>&1; then
+		echo "and $c"
+		command $abcscr "$@" > /tmp/o.xhtml
+		$c --headless --disable-gpu --print-to-pdf=$out /tmp/o.xhtml
+		rm /tmp/o.xhtml
+		return
+	fi
+done
+
+# check the required programs
+if command -v  >/dev/null 2>&1; then
+elif ! command -v rsvg-convert >/dev/null 2>&1; then
+	echo "$0: program 'rsvg-convert' not found - abort"
+	exit 1
+fi
+echo "and rsvg-convert"
 
 # build a ABC file (JS script) to change the font and page definitions
 # this solves the following problems:
